### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by tn** [mdubourg001/ssgo#16] opened 2021-12-12 17:54 UTC
```
deno install --unstable --allow-read --allow-write --allow-net --allow-run -q https://deno.land/x/ssgo/ssgo.ts
error: TS2339 [ERROR]: Property 'getIterator' does not exist on type 'ReadableStream<R>'.
  return res.readable.getIterator();
                      ~~~~~~~~~~~
    at https://deno.land/std@0.77.0/async/pool.ts:45:23
```
```
deno --version
deno 1.16.4 (release, aarch64-apple-darwin)
v8 9.7.106.15
typescript 4.4.2
```

**Comment by jpeterse** [comment] 2021-12-17 05:56
I just found this site generator, and was hoping to give it a try. It looks very promising, except, that it hasn't been updated in quite a while. Last update to 1.19 was in May, and last release was a year ago.

I tried to give it a look, and see if updating the referenced libraries would resolve the issue, but no.
Updating to current release of the libraries didn't resolve the issue.
I updated all references to current releases, even build a version without dependency of the old OAK framework. And updated to new release of Deno from today (1.17), and libraries to 0.118.

I have no idea where the reference to std@0.77 is made. I can capture the error in function runCreator in index.ts. but as mentioned, I have no idea what it is that are referring back to old standard library.

Don't know if this project is dead, given the long time that has past since last update. Would be a shame if that's the case though.

**Comment by mdubourg001** [comment] 2021-12-17 11:05
Hello there, thanks for your interest for the project !

I've not had much time lately to take care of it and maintain it but as some people seem to be interested I'll try to take care of it during the week-end 👌

**Comment by mdubourg001** [comment] 2021-12-17 14:53
Ok so I've upgraded the sources to use Deno's std@0.118.0 (latest) and refactored some code to match new APIs, could you confirm that the installation command works for you now ?

FIY the "std@0.77" related error was related to one of ssgo's dependencies, namely `oak` that was pinned an old version.

**Comment by jpeterse** [comment] 2021-12-17 18:10
Awesome to see this updated. Not sure about oak being the problem though.

I was working on an update that removed OAK entirely, as WebSockets are now part of native Deno, and as WS was removed in latest release of Deno in favor for the new WebSocket API.
Therefore I was working on an update to remove both legacy Deno.WS and oak, but I still got the error message.

I cloned 0.20.0, an get this.

```
deno run --unstable --allow-read --allow-write --allow-net --allow-run ../ssgo-0.20.0/ssgo.ts build
Check file:///home/jpeterse/ssgo-0.20.0/ssgo.ts
info ssgo 0.20.0
info Emptying dist directory...
info Running creators/index.ts...
Check file:///home/jpeterse/testssgo/creators/index.ts
error: Uncaught (in promise) TypeError: TS2339 [ERROR]: Property 'getIterator' does not exist on type 'ReadableStream<R>'.
  return res.readable.getIterator();
                      ~~~~~~~~~~~
    at https://deno.land/std@0.77.0/async/pool.ts:45:23
  const module = await import(`file://${tempModuleAbs}`)
                 ^
    at async importModule (file:///home/jpeterse/ssgo-0.20.0/src/utils.ts:315:18)
    at async runCreator (file:///home/jpeterse/ssgo-0.20.0/src/index.ts:411:18)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async file:///home/jpeterse/ssgo-0.20.0/src/index.ts:506:5
```

**Comment by jpeterse** [comment] 2021-12-17 18:57
hm, think I found a work-around.
Clear Deno cache.

Find Deno cache directory with Deno info.
Then clear the directory with rm -rf {DENO_DIR location}/*

then run SSGO build action again, and it builds without issue.

Why clearing cache works, I don't know.

**Comment by mdubourg001** [comment] 2021-12-17 20:45
Yes I've encountered similar cache issues with Deno multiple times already, I'm not sure where it comes from either...  

So did the install work as intended, can I close this issue ?

**Comment by jpeterse** [comment] 2021-12-17 21:57
works for me - I'll let @tn confirm it works from him as well

**Closed as completed** 2021-12-29 14:05 UTC

**Comment by amundo** [comment] 2022-03-03 13:46
May I ask how one goes about clearing the cache? I’m experiencing this error.

**Comment by mdubourg001** [comment] 2022-03-04 16:40
You should be able to force the reload of Deno cache by using the `--reload` flag:

```bash
deno install --unstable --allow-read --allow-write --allow-net --allow-run --reload https://deno.land/x/ssgo/ssgo.ts
```
